name: CI

on: workflow_dispatch

jobs:

  build:

    runs-on: ${matrix.buildplat[0]}
    strategy:
      # Ensure that a wheel builder finishes even if another fails
      fail-fast: false
      matrix:
        buildplat: [[ubuntu-latest, manylinux_x86_64],[ubuntu-latest, musllinux_x86_64],[macos-latest, macosx_*],[windows-latest, win_amd64],[windows-latest, win32],[windows-latest, win_arm64]]
        python: ["cp39", "cp310", "cp311", "cp312", "pp39"]
    steps:

      - uses: actions/checkout@v3
        with:
          repository: numpy/numpy
      - uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.12.0
        env:
          CIBW_BUILD: ${{ matrix.python }}-${{ matrix.buildplat[1] }}

      - uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.python }}-${{ startsWith(matrix.buildplat[1], 'macosx') && 'macosx' || matrix.buildplat[1] }}
          path: ./wheelhouse/*.whl
