name: CI

on: workflow_dispatch

jobs:

  build:

    runs-on: ${{ matrix.buildplat[0] }}
    strategy:
      # Ensure that a wheel builder finishes even if another fails
      fail-fast: false
      matrix:
        buildplat:
          - [ubuntu-latest, x86_64]
          - [ubuntu-latest, aarch64 ]
          - [macos-latest, x86_64]
          - [macos-latest, arm64]
          - [windows-latest, amd64]
          - [windows-latest, x86]
          - [windows-latest, arm64]
        python: ["cp311", "cp312"]
    steps:

      - uses: actions/checkout@v3
        with:
          repository: numpy/numpy
      - uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==2.12.0

      - name: Go to package
        run: cd numpy/numpy
      
      - name: Build wheels
        run: python -m cibuildwheel --arch ${{ matrix.buildplat[1] }}

      - uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.python }}-${{ startsWith(matrix.buildplat[1], 'macosx') && 'macosx' || matrix.buildplat[1] }}
          path: ./wheelhouse/*.whl
